<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>XiezhiCodeGuardLauncher</AssemblyName>
    <RootNamespace>XiezhiCodeGuardLauncher</RootNamespace>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
